# Generated by Django 4.1.1 on 2023-12-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_created',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='note',
            name='due_date',
            field=models.CharField(max_length=10),
        ),
    ]
