# Generated by Django 4.1.1 on 2023-12-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_note_date_created_alter_note_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='date_created',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='due_date',
            new_name='duedate',
        ),
        migrations.AddField(
            model_name='note',
            name='dead',
            field=models.BooleanField(default=False),
        ),
    ]
