# Generated by Django 4.1.1 on 2023-12-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_note_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='duedate',
            field=models.DateField(),
        ),
    ]
